version: "3"

services:
  db-mysql:
    container_name: db-mysql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=t!$easduhnc72DUIASHd7812y34
      - ACCEPT_EULA=Y
